### ISSUE TITLE
Expanded functionality

### ISSUE THREAD

**Issue by gbine** [iNavFlight/INAV-Rangefinder-I2C-interface#4]
Have you thought about building GPS functionality into this (just like the old MultiWii addon)?
Might be useful for those with limited UARTs,
IIRC,  Konstantin was using this method for GPS a year or so ago.
Just a thought.

Thanks for bringing SONAR back!

**Comment by digitalentity** [comment]
There is support for I2C-GPS using the same old multi-wii i2c-nav board, we didn't remove it.

**Comment by DzikuVx** [comment]
@gbine no, this is rangefinder only. Might evolve into hybrid rangefinder solution, but it will be always limited to rangefinders only.

And sonar is not yet really back. Might be, but not yet :)
