### ISSUE TITLE
HC-SR04 Digital I2C Module

### ISSUE THREAD

**Issue by DimaVIII** [iNavFlight/INAV-Rangefinder-I2C-interface#5]
Wouldn't this HC-SR04 Digital I2C Module from Banggood do the same as this scrip?

https://www.banggood.com/Flight-Controller-Ultrasonic-Wave-Altitude-Digital-I2C-Module-For-PIXHAWK-PIX-APM-PIXHACK-p-1175720.html

I didn't read the iNAV code, just wondering if it is necessary to build  this converter or just use a device that is already converting the output to I2C.

**Comment by DzikuVx** [comment]
Probably but 
```
Digital Module, with high accuracy, up to 7m,much higher than analog module
Highly output accuracy in 0.01m, range accuracy is 4.99m
```
WTF? Are they serious?

**Comment by digitalentity** [comment]
Looks like a crappy HC-SR04 sonar + Atmega board. This means it's not nearly 7m and definitely useless on quads.

**Comment by DimaVIII** [comment]
Yeah this are Banggood descriptions... they never know what they are actually selling there.
However I will build one with this script, was just wondering.
The Rangefinder is supported by all newer FC with I2C pins and iNAV 1.7.3, right?

**Comment by DzikuVx** [comment]
Yes, I2C on FC is required. But please use US-100 not HC-SR04 which is crap
